In [1]:
#Dependencies
%matplotlib notebook
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json

In [37]:
#2015 json file read
jsonfile = "2015_codes.json"
json_data=open(jsonfile).read()
data = json.loads(json_data)

df = pd.DataFrame.from_dict(data['113_cause_recode'], orient='index')

df = df.rename(columns={0:"113_cause_recode"})
df

                                      113_cause_recode
001                    Salmonella infections (A01-A02)
002                Shigellosis and amebiasis (A03,A06)
003  Certain other intestinal infections (A04,A07-A09)
004                             Tuberculosis (A16-A19)
005                     Respiratory tuberculosis (A16)
006                       Other tuberculosis (A17-A19)
007                               Whooping cough (A37)
008             Scarlet fever and erysipelas (A38,A46)
009                      Meningococcal infection (A39)
010                               Septicemia (A40-A41)
011                                 Syphilis (A50-A53)
012                          Acute poliomyelitis (A80)
013  Arthropod-borne viral encephalitis (A83-A84,A8...
014                                      Measles (B05)
015                          Viral hepatitis (B15-B19)
016  Human immunodeficiency virus (HIV) disease (B2...
017                                  Malaria (B50-B54)
018  Other and unspecified infectious and parasitic...
019                      Malignant neoplasms (C00-C97)
020  Malignant neoplasms of lip, oral cavity and ph...
021              Malignant neoplasm of esophagus (C15)
022                Malignant neoplasm of stomach (C16)
023  Malignant neoplasms of colon, rectum and anus ...
024  Malignant neoplasms of liver and intrahepatic ...
025               Malignant neoplasm of pancreas (C25)
026                 Malignant neoplasm of larynx (C32)
027  Malignant neoplasms of trachea, bronchus and l...
028                   Malignant melanoma of skin (C43)
029                 Malignant neoplasm of breast (C50)
030           Malignant neoplasm of cervix uteri (C53)
..                                                 ...
106          Pregnancy with abortive outcome (O00-O07)
107  Other complications of pregnancy, childbirth a...
108  Certain conditions originating in the perinata...
109  Congenital malformations, deformations and chr...
110  Symptoms, signs and abnormal clinical and labo...
111  All other diseases (Residual) (D65-E07,E15-E34...
112  Accidents (unintentional injuries) (V01-X59,Y8...
113                  Transport accidents (V01-V99,Y85)
114  Motor vehicle accidents (V02-V04,V09.0,V09.2,V...
115  Other land transport accidents (V01,V05-V06,V0...
116  Water, air and space, and other and unspecifie...
117               Nontransport accidents (W00-X59,Y86)
118                                    Falls (W00-W19)
119         Accidental discharge of firearms (W32-W34)
120       Accidental drowning and submersion (W65-W74)
121  Accidental exposure to smoke, fire and flames ...
122  Accidental poisoning and exposure to noxious s...
123  Other and unspecified nontransport accidents a...
124  Intentional self-harm (suicide) (*U03,X60-X84,...
125  Intentional self-harm (suicide) by discharge o...
126  Intentional self-harm (suicide) by other and u...
127       Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)
128  Assault (homicide) by discharge of firearms (*...
129  Assault (homicide) by other and unspecified me...
130                     Legal intervention (Y35,Y89.0)
131  Events of undetermined intent (Y10-Y34,Y87.2,Y...
132  Discharge of firearms, undetermined intent (Y2...
133  Other and unspecified events of undetermined i...
134   Operations of war and their sequelae (Y36,Y89.1)
135  Complications of medical and surgical care (Y4...

[135 rows x 1 columns]

In [22]:
data_file = 'sample5death05_15.csv'
data_file_pd = pd.read_csv(data_file)
data_df = pd.DataFrame(data_file_pd)
data_df.dtypes

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Unnamed: 0                               int64
113_cause_recode                         int64
130_infant_cause_recode                float64
358_cause_recode                       float64
39_cause_recode                        float64
Unnamed: 0.1                             int64
Unnamed: 0.1.1                         float64
activity_code                          float64
age_recode_12                          float64
age_recode_27                          float64
age_recode_52                          float64
autopsy                                 object
current_data_year                        int64
day_of_week_of_death                     int64
detail_age                               int64
detail_age_type                        float64
education_2003_revision                float64
hispanic_origin                        float64
hispanic_originrace_recode               int64
icd_code_10th_revision                  object
infant_age_recode_22                   float64
injury_at_work                          object
manner_of_death                        float64
marital_status                          object
method_of_disposition                   object
month_of_death                           int64
place_of_death_and_decedents_status      int64
race_recode_3                          float64
race_recode_5                            int64
resident_status                          int64
sex                                     object
dtype: object

In [69]:
#check to see index
df.index

Index(['001', '002', '003', '004', '005', '006', '007', '008', '009', '010',
       ...
       '126', '127', '128', '129', '130', '131', '132', '133', '134', '135'],
      dtype='object', length=135)

In [3]:
#check to see columns
data_df.columns

Index(['Unnamed: 0', '113_cause_recode', '130_infant_cause_recode',
       '358_cause_recode', '39_cause_recode', 'Unnamed: 0.1', 'Unnamed: 0.1.1',
       'activity_code', 'age_recode_12', 'age_recode_27', 'age_recode_52',
       'autopsy', 'current_data_year', 'day_of_week_of_death', 'detail_age',
       'detail_age_type', 'education_2003_revision', 'hispanic_origin',
       'hispanic_originrace_recode', 'icd_code_10th_revision',
       'infant_age_recode_22', 'injury_at_work', 'manner_of_death',
       'marital_status', 'method_of_disposition', 'month_of_death',
       'place_of_death_and_decedents_status', 'race_recode_3', 'race_recode_5',
       'resident_status', 'sex'],
      dtype='object')

In [72]:
#See data types
data_df.head()
data_df['113_cause_recode'].dtypes

dtype('int64')

In [75]:
#reset index
df.reset_index(inplace=True)

In [76]:
df.head()

  index                                   113_cause_recode
0   001                    Salmonella infections (A01-A02)
1   002                Shigellosis and amebiasis (A03,A06)
2   003  Certain other intestinal infections (A04,A07-A09)
3   004                             Tuberculosis (A16-A19)
4   005                     Respiratory tuberculosis (A16)

In [79]:
#Rename column to better fit description
new_df = df.rename(columns={'113_cause_recode':'description'})
new_df.head()

  index                                        description
0   001                    Salmonella infections (A01-A02)
1   002                Shigellosis and amebiasis (A03,A06)
2   003  Certain other intestinal infections (A04,A07-A09)
3   004                             Tuberculosis (A16-A19)
4   005                     Respiratory tuberculosis (A16)

In [83]:
#rename index to match code
new_df.rename(columns={'index':'113_cause_recode'},inplace=True)
new_df.head()

  113_cause_recode                                        description
0              001                    Salmonella infections (A01-A02)
1              002                Shigellosis and amebiasis (A03,A06)
2              003  Certain other intestinal infections (A04,A07-A09)
3              004                             Tuberculosis (A16-A19)
4              005                     Respiratory tuberculosis (A16)

In [87]:
#Change datatype to integer
new_df['113_cause_recode'] = new_df['113_cause_recode'].astype('int')
new_df.head()

   113_cause_recode                                        description
0                 1                    Salmonella infections (A01-A02)
1                 2                Shigellosis and amebiasis (A03,A06)
2                 3  Certain other intestinal infections (A04,A07-A09)
3                 4                             Tuberculosis (A16-A19)
4                 5                     Respiratory tuberculosis (A16)

In [90]:
#New merged data set ( still needs cleaning)

death_df = data_df.join(new_df, on='113_cause_recode', lsuffix='_x', rsuffix='_y')
death_df.head()

,Unnamed: 0,113_cause_recode_x,130_infant_cause_recode,358_cause_recode,39_cause_recode,Unnamed: 0.1,Unnamed: 0.1.1,activity_code,age_recode_12,age_recode_27,...,marital_status,method_of_disposition,month_of_death,place_of_death_and_decedents_status,race_recode_3,race_recode_5,resident_status,sex,113_cause_recode_y,description
0,0,67,NaN,NaN,NaN,12710949,12710949.0,NaN,NaN,NaN,...,W,U,10,6,NaN,1,1,M,68.0,"All other forms of heart disease (I26-I28,I34-..."
1,1,95,NaN,NaN,NaN,4686059,4686059.0,NaN,NaN,NaN,...,D,C,9,1,NaN,1,1,M,96.0,Cholelithiasis and other disorders of gallblad...
2,2,70,NaN,NaN,NaN,6762380,6762380.0,NaN,NaN,NaN,...,D,C,11,4,NaN,1,1,F,71.0,Atherosclerosis (I70)
3,3,68,NaN,NaN,NaN,12325960,12325960.0,NaN,NaN,NaN,...,M,B,1,4,NaN,1,1,M,69.0,Essential (primary) hypertension and hypertens...
4,4,24,NaN,NaN,NaN,491263,491263.0,NaN,NaN,NaN,...,M,B,4,4,NaN,1,1,M,25.0,Malignant neoplasm of pancreas (C25)

In [92]:
death_df.columns

Index(['Unnamed: 0', '113_cause_recode_x', '130_infant_cause_recode',
       '358_cause_recode', '39_cause_recode', 'Unnamed: 0.1', 'Unnamed: 0.1.1',
       'activity_code', 'age_recode_12', 'age_recode_27', 'age_recode_52',
       'autopsy', 'current_data_year', 'day_of_week_of_death', 'detail_age',
       'detail_age_type', 'education_2003_revision', 'hispanic_origin',
       'hispanic_originrace_recode', 'icd_code_10th_revision',
       'infant_age_recode_22', 'injury_at_work', 'manner_of_death',
       'marital_status', 'method_of_disposition', 'month_of_death',
       'place_of_death_and_decedents_status', 'race_recode_3', 'race_recode_5',
       'resident_status', 'sex', '113_cause_recode_y', 'description'],
      dtype='object')

In [112]:
death_df_slice = death_df[['Unnamed: 0',
                           '113_cause_recode_x',
                           'age_recode_52','autopsy',
                           'current_data_year',
                           'day_of_week_of_death',
                           'detail_age',
                           'education_2003_revision',
                           'hispanic_origin',
                           'injury_at_work',
                           'manner_of_death',
                           'marital_status',
                           'method_of_disposition',
                           'month_of_death',
                           'place_of_death_and_decedents_status',
                           'race_recode_5',
                           'sex',
                           'description']]

In [178]:
death_df_slice['method_of_disposition']

0          U
1          C
2          C
3          B
4          B
5          C
6          C
7          B
8          C
9          C
10         C
11         C
12         C
13         C
14         B
15         B
16         B
17         B
18         B
19         C
20         C
21         U
22         U
23         U
24         C
25         C
26         C
27         B
28         B
29         C
          ..
1386003    U
1386004    C
1386005    B
1386006    U
1386007    B
1386008    U
1386009    B
1386010    U
1386011    U
1386012    U
1386013    B
1386014    C
1386015    C
1386016    R
1386017    C
1386018    B
1386019    B
1386020    B
1386021    U
1386022    U
1386023    U
1386024    U
1386025    B
1386026    U
1386027    C
1386028    B
1386029    B
1386030    B
1386031    B
1386032    U
Name: method_of_disposition, Length: 1386033, dtype: object

In [177]:
death_group_description = death_df_slice.groupby('113_cause_recode_x')['description'].count()
death_group_description_df = pd.DataFrame(death_group_description)
death_group_description_df
death_group_description_df
#death_count = death_group_description['description'].count()
#death_count = death_group_description['113_cause_recode_x'].value_counts()
#death_count_chart = death_group_description_df.plot(kind='bar')
#death_count_chart.set_xlabel('Cause')
#death_count_chart.set_ylabel('# of Deaths')

#top_death_count = death_group_description[]
#top_death_count = pd.DataFrame(death_group_description['description'].())

                    description
113_cause_recode_x
1                            19
2                             2
3                          4872
5                           240
6                            84
7                             9
8                             1
9                            43
10                        20010
11                           18
13                            3
15                         4157
16                         4797
17                            7
18                         3308
20                         4725
21                         7857
22                         6293
23                        29040
24                        11396
25                        20472
26                         2050
27                        86675
28                         4912
29                        22883
30                         2236
31                         4568
32                         8004
33                        15509
34                         7379
...                         ...
99                         1145
100                       24740
101                          11
102                         394
103                         295
104                          70
106                          16
107                         521
108                        7190
109                        5562
110                       19964
111                      151577
114                       21673
115                         599
116                         992
118                       14577
119                         296
120                        2000
121                        1560
122                       18893
123                        9518
125                       10704
126                       10462
128                        6736
129                        2952
130                         238
132                         116
133                        2683
134                          13
135                           0

[111 rows x 1 columns]

In [161]:
#death_group_description_df.groupby(level=[0]).largest(10)
death_group_description1 = death_df.groupby('113_cause_recode_x')['description']
death_group_description_df1 = pd.DataFrame(death_group_description1)
#death_group_description_df1

ValueError: DataFrame constructor not properly called!

In [173]:
death_group_description_df.sort_values('description', ascending = False, inplace= True)
death_count_chart = death_group_description_df.plot(kind='bar')
death_count_chart.set_xlabel('Cause')
death_count_chart.set_ylabel('# of Deaths')
#plt.xticks(10)

Text(0, 0.5, '# of Deaths')

In [174]:
death_group_description_df.sort_values('description', ascending = False, inplace= True)
death_group_description_df.head(10)

                    description
113_cause_recode_x
111                      151577
63                       110383
27                        86675
70                        73432
59                        69563
86                        68801
68                        66645
52                        45953
46                        40299
43                        36472

In [ ]:
death_df_slice =

In [91]:
data_df.head()

,Unnamed: 0,113_cause_recode,130_infant_cause_recode,358_cause_recode,39_cause_recode,Unnamed: 0.1,Unnamed: 0.1.1,activity_code,age_recode_12,age_recode_27,...,injury_at_work,manner_of_death,marital_status,method_of_disposition,month_of_death,place_of_death_and_decedents_status,race_recode_3,race_recode_5,resident_status,sex
0,0,67,NaN,NaN,NaN,12710949,12710949.0,NaN,NaN,NaN,...,U,7.0,W,U,10,6,NaN,1,1,M
1,1,95,NaN,NaN,NaN,4686059,4686059.0,NaN,NaN,NaN,...,U,7.0,D,C,9,1,NaN,1,1,M
2,2,70,NaN,NaN,NaN,6762380,6762380.0,NaN,NaN,NaN,...,U,7.0,D,C,11,4,NaN,1,1,F
3,3,68,NaN,NaN,NaN,12325960,12325960.0,NaN,NaN,NaN,...,U,7.0,M,B,1,4,NaN,1,1,M
4,4,24,NaN,NaN,NaN,491263,491263.0,NaN,NaN,NaN,...,U,7.0,M,B,4,4,NaN,1,1,M

In [41]:

x = ["{0:03}".format(i) for i in range(135)]

In [68]:
Cause_113_recode = {'113_cause_recode': [x],
                 '113_cause_meaning': [y]}

cause_113code_df = pd.DataFrame(Cause_113_recode)
cause_113code_df

,113_cause_recode,113_cause_meaning
0,"[000, 001, 002, 003, 004, 005, 006, 007, 008, ...","[001Salmonella infections (A01-A02), 002Shigel..."

In [63]:
for line in y.iter_lines():
  line = line.replace(x, "")

AttributeError: 'list' object has no attribute 'iter_lines'

In [62]:
i=3
while i < len(y):
    element = y[i] 
    del(element)
    if i < (element):
        del y[i]
    else:
        i+=1

NameError: name 'check' is not defined

In [57]:
y = ['001Salmonella infections (A01-A02)',
'002Shigellosis and amebiasis (A03,A06)',
'003Certain other intestinal infections (A04,A07-A09)',
'0041 Tuberculosis (A16-A19)',
'005Respiratory tuberculosis (A16)',
'006Other tuberculosis (A17-A19)',
'007Whooping cough (A37)',
'008Scarlet fever and erysipelas (A38,A46)',
'009Meningococcal infection (A39)',
'0103 Septicemia (A40-A41)',
'011Syphilis (A50-A53)',
'012Acute poliomyelitis (A80)',
'013Arthropod-borne viral encephalitis (A83-A84,A85.2)',
'014Measles (B05),'
'015Viral hepatitis (B15-B19)',
'016Human immunodeficiency virus (HIV) disease (B20-B24)',
'017Malaria (B50-B54)',
'018Other and unspecified infectious and parasitic diseases and their sequelae (A00,A05,A20-A36,A42-A44,A48-A49,A54-A79,A81-A82,A85.0-A85.1,A85.8, A86-B04,B06-B09,B25-B49,B55-B99)',
'0191Malignant neoplasms (C00-C97)',
'020Malignant neoplasms of lip, oral cavity and pharynx (C00-C14)',
'021Malignant neoplasm of esophagus (C15)',
'022Malignant neoplasm of stomach (C16)',
'023Malignant neoplasms of colon, rectum and anus (C18-C21)',
'024Malignant neoplasms of liver and intrahepatic bile ducts (C22)',
'025Malignant neoplasm of pancreas (C25)',
'026Malignant neoplasm of larynx (C32)',
'027Malignant neoplasms of trachea, bronchus and lung (C33-C34)',
'028Malignant melanoma of skin (C43)',
'029Malignant neoplasm of breast (C50)',
'0302 Malignant neoplasm of cervix uteri (C53)',
'0312 Malignant neoplasms of corpus uteri and uterus, part unspecified (C54-C55)',
'0322 Malignant neoplasm of ovary (C56)',
'0331 Malignant neoplasm of prostate (C61)',
'034Malignant neoplasms of kidney and renal pelvis (C64-C65)',
'035Malignant neoplasm of bladder (C67)',
'036"Malignant neoplasms of meninges, brain and other parts of central nervous system (C70-C72)',
'037"1Malignant neoplasms of lymphoid, hematopoietic and related tissue (C81-C96)',
'038Hodgkin''s disease (C81)',
'039Non-Hodgkins' 'lymphoma (C82-C85)',
'040Leukemia (C91-C95)',
'041"Multiple myeloma and immunoproliferative neoplasms (C88,C90)',
'042"Other and unspecified malignant neoplasms of lymphoid, hematopoietic and related tissue (C96)',
'043"All other and unspecified malignant neoplasms (C17,C23-C24,C26-C31,C37-C41, C44-C49,C51-C52,C57-C60,C62-C63,C66,C68-C69,C73-C80,C97)',
'044"In situ neoplasms, benign neoplasms and neoplasms of uncertain or unknown behavior (D00-D48)',
'045Anemias (D50-D64)',
'0463 Diabetes mellitus (E10-E14)',
'047Nutritional deficiencies (E40-E64)',
'048Malnutrition (E40-E46)',
'049Other nutritional deficiencies (E50-E64)',
'050Meningitis (G00,G03)',
'051Parkinson''s' 'disease (G20-G21)',
'052Alzheimers' 'disease (G30)',
'0531 Major cardiovascular diseases (I00-I78)',
'0541Diseases of heart (I00-I09,I11,I13,I20-I51)',
'055Acute rheumatic fever and chronic rheumatic heart diseases (I00-I09)',
'056Hypertensive heart disease (I11)',
'057Hypertensive heart and renal disea',
'0581 Ischemic heart diseases (I20-I25)',
'059Acute myocardial infarction (I21-I22)',
'060Other acute ischemic heart diseases (I24)',
'0611 Other forms of chronic ischemic heart disease (I20,I25)',
'062Atherosclerotic cardiovascular disease, so described (I25.0)',
'063All other forms of chronic ischemic heart disease(I20,I25.1-I25.9)',
'0641Other heart diseases (I26-I51)',
'065Acute and subacute endocarditis (I33)',
'066'"Diseases of pericardium and acute myocarditis (I30-I31,I40)",
'067Heart failure (I50)',
'068'"All other forms of heart disease (I26-I28,I34-I38,I42-I49,I51)",
'069',"Essential (primary) hypertension and hypertensive renal disease (I10,I12,I15)",
'070'',Cerebrovascular diseases (I60-I69)',
'071'',Atherosclerosis (I70)',
'072'',1Other diseases of circulatory system (I71-I78)',
'073'',Aortic aneurysm and dissection (I71)',
'074Other diseases of arteries, arterioles and capillaries (I72-I78)',
'075'',Other disorders of circulatory system (I80-I99)',
'076'',1Influenza and pneumonia (J09-J18)',
'077'',Influenza (J09-J11)',
'078'',Pneumonia (J12-J18)',
'079',"1Other acute lower respiratory infections (J20-J22,U04)",
'080'',Acute bronchitis and bronchiolitis (J20-J21)',
'081'"Other and unspecified acute lower respiratory infection (J22,U04)",
'082''1Chronic lower respiratory diseases (J40-J47)',
'083'"Bronchitis, chronic and unspecified (J40-J42)",
'084''3 Emphysema (J43)',
'085''Asthma (J45-J46)',
'086'"Other chronic lower respiratory diseases (J44,J47)",
'087'"Pneumoconioses and chemical effects (J60-J66,J68)",
'088,Pneumonitis due to solids and liquids (J69)',
'089,Other diseases of respiratory system (J00-J06,J30-J39,J67,J70-J98)',
'090,Peptic ulcer (K25-K28)',
'091,Diseases of appendix (K35-K38)',
'092,Hernia (K40-K46)',
'0931Chronic liver disease and cirrhosis (K70,K73-K74)',
'094Alcoholic liver disease (K70)',
'095,Other chronic liver disease and cirrhosis (K73-K74)',
'096,Cholelithiasis and other disorders of gallbladder (K80-K82)',
'097,"1Nephritis, nephrotic syndrome and nephrosis (N00-N07,N17-N19,N25-N27)',
'098,"Acute and rapidly progressive nephritic and nephrotic syndrome (N00-N01,N04)',
'099,"Chronic glomerulonephritis, nephritis and nephropathy not specified as acute or chronic, and renal sclerosis unspecified (N02-N03,N05-N07,N26)',
'100,Renal failure (N17-N19)',
'101,"Other disorders of kidney (N25,N27)',
'102,"Infections of kidney (N10-N12,N13.6,N15.1)',
'103,1 Hyperplasia of prostate (N40)',
'104,2 Inflammatory diseases of female pelvic organs (N70-N76)',
'105,"1 2 7 Pregnancy, childbirth and the puerperium (O00-O99)',
'106,2 7 Pregnancy with abortive outcome (O00-O07)',
'107,"2 7 Other complications of pregnancy, childbirth and the puerperium (O10-O99)',
'108,Certain conditions originating in the perinatal period (P00-P96)',
'109,"Congenital malformations, deformations and chromosomal abnormalities (Q00-Q99)',
'110,"Symptoms, signs and abnormal clinical and laboratory findings, notelsewhere classified (R00-R99)',
'111,"All other diseases (Residual) (D65-E07,E15-E34,E65-F99,G04-G14,G23-G25,G31-H93,',
'112,"1 Accidents (unintentional injuries) (V01-X59,Y85-Y86)',
'113,"1Transport accidents (V01-V99,Y85)',
'114,"Motor vehicle accidents (V02-V04,V09.0,V09.2,V12-V14,V19.0-V19.2,,V19,.4-V19.6,V20-V79,V80.3-V80.5,V81.0-V81.1,V82.0-V82.1,V83-V86,V87.0-V87.8,V88.0-V88.8,V89.0,V89.2)",115,"Other land transport accidents (V01,V05-V06,V09.1,V09.3-V09.9, V10-V11,',
'116,"Water, air and space, and other and unspecified transport accidents and their sequelae (V90-V99,Y85)',
'117,"1 Nontransport accidents (W00-X59,Y86)',
'118,Falls (W00-W19)',
'119,Accidental discharge of firearms (W32-W34)',
'120,Accidental drowning and submersion (W65-W74)',
'121,"Accidental exposure to smoke, fire and flames (X00-X09)',
'122,Accidental poisoning and exposure to noxious substances (X40-X49)',
'123,"Other and unspecified nontransport accidents and their sequelae (W20-W31,W35-W64,W75-W99,X10-X39,X50-X59,Y86)',
'124,"1 1 Intentional self-harm (suicide) (*U03,X60-X84,Y87.0)',
'125,1 Intentional self-harm (suicide) by discharge of firearms (X72-X74)',
'126,"1 Intentional self-harm (suicide) by other and unspecified means and their sequelae (*U03,X60-X71,X75-X84,Y87.0)',
'127,"1 Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)',
'128,"Assault (homicide) by discharge of firearms (*U01.4,X93-X95)',
'129,"Assault (homicide) by other and unspecified means and their sequelae (*U01.0-*U01.3,*U01.5-*U01.9,*U02,X85-X92,X96-Y09,Y87.1)',
'130,"Legal intervention(Y35,Y89.0)',
'131,"1 Events of undetermined intent (Y10-Y34,Y87.2,Y89.9)',
'132,"Discharge of firearms, undetermined intent (Y22-Y24)',
'133,"Other and unspecified events of undetermined intent and their sequelae (Y10-Y21,Y25-Y34,Y87.2,Y89.9)',
'134,"Operations of war and their sequelae (Y36,Y89.1)',
'135,"Complications of medical and surgical care (Y40-Y84,Y88)']